version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_DB: events
      POSTGRES_PASSWORD: $DATABASE_PASS
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habrpguser -d habrdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data

  keks-event:
    image: alexeav/keksevents:${KEKS_EVENTS_VER}
    container_name: keks-events
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  pg_data:
