// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Event struct {
	ID        string    `json:"id"`
	DateStart time.Time `json:"dateStart"`
	DateEnd   time.Time `json:"dateEnd"`
	Status    bool      `json:"status"`
	Priority  int       `json:"priority"`
	Group     int       `json:"group"`
	EventName string    `json:"eventName"`
	Text      string    `json:"text"`
	UserID    string    `json:"userId"`
	User      *User     `json:"user"`
}

type Mutation struct {
}

type NewEvent struct {
	EventName string    `json:"eventName"`
	Text      string    `json:"text"`
	DateStart time.Time `json:"dateStart"`
	DateEnd   time.Time `json:"dateEnd"`
	UserID    string    `json:"userId"`
}

type Query struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
