// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Event struct {
	ID          string `json:"id"`
	Start       string `json:"start"`
	End         string `json:"end"`
	Status      bool   `json:"status"`
	Priority    int    `json:"priority"`
	Group       int    `json:"group"`
	Title       string `json:"title"`
	Description string `json:"description"`
	User        *User  `json:"user"`
}

type GetEvent struct {
	ID string `json:"id"`
}

type Mutation struct {
}

type NewEvent struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Start       string `json:"start"`
	End         string `json:"end"`
}

type Query struct {
}

type UpdateEvent struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Start       string `json:"start"`
	End         string `json:"end"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
